"""
Database restore management command.

Restores application data from a JSON/XML dump generated by dbbackup.

Usage:
    python manage.py dbrestore -i backup_20260312_143000.json
    python manage.py dbrestore -i backup.json --flush --force
    python manage.py dbrestore -i backup.json --dry-run
"""

import os

from django.contrib.auth.models import User
from django.core.management import call_command
from django.core.management.base import BaseCommand, CommandError

from attendance.models import (
    Attendance,
    AttendanceStudent,
    AttendanceToken,
    Course,
    CourseEnrollment,
    Lecturer,
    Student,
    WebAuthnCredential,
)


class Command(BaseCommand):
    help = 'Restore database data from a backup file created by dbbackup'

    def add_arguments(self, parser):
        parser.add_argument(
            '--input', '-i',
            required=True,
            type=str,
            help='Backup file path (JSON or XML)',
        )
        parser.add_argument(
            '--flush',
            action='store_true',
            default=False,
            help='Flush database before restoring (recommended for full restore)',
        )
        parser.add_argument(
            '--force',
            action='store_true',
            default=False,
            help='Skip safety checks/prompts for non-interactive automation',
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            default=False,
            help='Validate restore inputs and show what would happen (no writes)',
        )

    def _has_existing_data(self):
        """Detect whether the DB already has user/application records."""
        return any([
            User.objects.exists(),
            Lecturer.objects.exists(),
            Student.objects.exists(),
            Course.objects.exists(),
            CourseEnrollment.objects.exists(),
            Attendance.objects.exists(),
            AttendanceStudent.objects.exists(),
            AttendanceToken.objects.exists(),
            WebAuthnCredential.objects.exists(),
        ])

    def handle(self, *args, **options):
        input_path = options['input']
        do_flush = options['flush']
        force = options['force']
        dry_run = options['dry_run']

        if not os.path.exists(input_path):
            raise CommandError(f'Backup file not found: {input_path}')

        file_size = os.path.getsize(input_path)
        self.stdout.write(f'Backup file: {input_path} ({file_size:,} bytes)')

        has_existing_data = self._has_existing_data()
        if has_existing_data and not do_flush and not force:
            raise CommandError(
                'Existing data detected. Use --flush for a clean restore, '
                'or --force to attempt restore without flushing.'
            )

        if dry_run:
            action = 'would flush and restore' if do_flush else 'would restore'
            self.stdout.write(self.style.SUCCESS(f'DRY-RUN: Command {action} from {input_path}'))
            return

        if do_flush:
            self.stdout.write('Flushing database …')
            call_command('flush', '--no-input', verbosity=0)
            self.stdout.write(self.style.SUCCESS('Database flushed.'))

        self.stdout.write('Restoring data …')
        try:
            call_command('loaddata', input_path, verbosity=0)
        except Exception as exc:
            raise CommandError(f'Restore failed: {exc}') from exc

        self.stdout.write(self.style.SUCCESS(f'Restore completed successfully from {input_path}'))
