# Generated by Django 5.0.7 on 2026-02-14 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_course_is_active_alter_student_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', through='attendance.CourseEnrollment', to='attendance.student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['course', 'date'], name='attendance__course__abd009_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['is_active'], name='attendance__is_acti_a7c189_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='attendance__student_40cee0_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['programme_of_study'], name='attendance__program_a5d6ca_idx'),
        ),
    ]
