# Generated by Django 5.0.7 on 2026-02-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_add_qr_code_to_attendance_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='student',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Both Email and SMS'), ('none', 'None')], default='both', max_length=10),
        ),
    ]
