# Generated by Django 5.0.7 on 2026-03-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_attendancestudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='require_two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='require_two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='is_two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='require_two_factor_auth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='two_factor_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
