# Generated by Django 5.0.7 on 2026-03-16 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_add_webauthn_credential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['created_at'], name='attendance__created_a6132d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['ended_at'], name='attendance__ended_a_9002b5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancestudent',
            index=models.Index(fields=['marked_at'], name='attendance__marked__dfa20d_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancetoken',
            index=models.Index(fields=['expires_at'], name='attendance__expires_31358b_idx'),
        ),
    ]
