# Generated by Django 5.2 on 2026-04-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_lecturer_fcm_token_student_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='join_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
