# Generated by Django 5.2 on 2026-05-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_course_join_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='radius_meters',
            field=models.PositiveIntegerField(default=50, help_text='Geofencing radius in meters for this session'),
        ),
    ]
