# Generated by Django 5.2 on 2026-05-03 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_add_radius_meters_to_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['year'], name='attendance__year_07dcd5_idx'),
        ),
    ]
