# Generated by Django 5.2 on 2026-06-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_populate_course_join_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='notification_preference',
            field=models.CharField(choices=[('email', 'Email Only'), ('none', 'None')], default='email', max_length=10),
        ),
    ]
